# Day 02: Creating and Manipulating Arrays

These challenges will help you solidify you understanding of NumPy arrays for data analysis in Python. By completing these tasks, you'll learn how to create array, how to check array size and shape, and how to maipulate arrays.

1. Write code to import NumPy into your script. Check the version of NumPy installed.

2. Here is a list below:
`list1 = [2, 3, 4, 6]`

- Create a 1D array from the list above.
- Write another line of code to check the `shape` and `size` of your array.
- Write a function (Python function) that takes this array and returns a new array with all the values in the original array reversed.

3. `list2 = [8, 10, 12, 14]`

- Create an array from the `list1` and `list2`.
- Then write code to check the shape, dimensions, and data type of the aray.

4. `list3 = [16, 18, 20, 22.1]`

- Create an array from `list1`, `list2` and `list3`. Take note that some of the lists contain floats,
- Create an array that will havean `int64` data type

5. Is it possible to create an array of both floats and integers?

# Day 02: Respostas

## 1.

In [1]:
import numpy as np

print(f"NumPy version: {np.__version__}")

NumPy version: 2.4.1


---

## 2.

In [3]:
list1 = [2, 3, 4, 6]
list1

[2, 3, 4, 6]

In [5]:
arr = np.array(list1)
arr

array([2, 3, 4, 6])

In [6]:
arr.shape

(4,)

In [7]:
len(arr)

4

In [9]:
def reverse_array(arr):
    new_array = arr[::-1]
    return np.array(new_array)

reverse_array(arr)

array([6, 4, 3, 2])

---

## 3

In [13]:
list1

[2, 3, 4, 6]

In [14]:
list2 = [8, 10, 12, 14]
list2

[8, 10, 12, 14]

In [16]:
arr2 = np.array([list1, list2])
arr2

array([[ 2,  3,  4,  6],
       [ 8, 10, 12, 14]])

In [17]:
arr2.shape

(2, 4)

In [18]:
arr2.ndim

2

In [19]:
arr2.dtype

dtype('int64')

---

## 4

In [20]:
list1

[2, 3, 4, 6]

In [21]:
list2

[8, 10, 12, 14]

In [22]:
list3 = [16, 18, 20, 22.1]
list3

[16, 18, 20, 22.1]

In [29]:
arr3 = np.array([list1, list2, list3])
arr3

array([[ 2. ,  3. ,  4. ,  6. ],
       [ 8. , 10. , 12. , 14. ],
       [16. , 18. , 20. , 22.1]])

In [30]:
arr3.dtype

dtype('float64')

In [32]:
new_arr3 = arr3.astype(np.int64)
new_arr3

array([[ 2,  3,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [33]:
new_arr3.dtype

dtype('int64')

---

## 5 

Não, arrays são homogêneo, ou seja, todos os elementos têm o mesmo `dtype`, é o que os torna rápidos possibilitando operações vetorizadas.

# Parecer técnico — Day 02 (NumPy arrays)

### 1) Resumo executivo

Você cumpriu praticamente todos os requisitos práticos do dia: criação de arrays 1D/2D, inspeção de `shape/ndim/dtype` e conversão de tipo com `astype`. O principal ponto a corrigir é conceitual: a resposta da Q5 (“não é possível ter ints e floats”) conflita com a própria prática da Q4 e com o comportamento real do NumPy (promoção de tipo).

### 2) Pontuação e nota

Rubrica (core_spec):

* Correção e aderência aos requisitos (45%)
* Raciocínio e interpretação (20%)
* Qualidade e legibilidade do código (20%)
* Eficiência e boas práticas de dados (15%)

Notas por critério (0–10):

* Correção/requisitos: 8.00 (Q5 incorreta; demais ok)
* Raciocínio/interpretação: 7.50 (explicação boa sobre homogeneidade, mas conclusão errada)
* Código/legibilidade: 8.50 (simples, executa, pequenas melhorias possíveis)
* Eficiência/boas práticas: 8.50 (ok para o escopo; um ponto por redundâncias pequenas)

Cálculo:
Nota = 0.45·8.00 + 0.20·7.50 + 0.20·8.50 + 0.15·8.50
Nota final: **7.98/10**

### 3) Correções técnicas (por questão)

Q1. Import e versão
Está correto (`import numpy as np` e print da versão).

Q2. 1D array, `shape` e `size`, função de reversão

* Você checou `arr.shape` corretamente. Para “size”, o mais direto é `arr.size` (em 1D, `len(arr)` funciona, mas não generaliza para dimensões maiores do mesmo jeito).
* A função `reverse_array` está correta. Pequena melhoria: o slice `arr[::-1]` já é `ndarray`, então `np.array(new_array)` é redundante.

Trecho mais idiomático (só como ajuste, não “re-solução”):

```python
def reverse_array(arr):
    return arr[::-1]
```

Q3. Array com `list1` e `list2`, `shape`, `ndim`, `dtype`
Correto: `arr2` fica 2D (2,4), `ndim` e `dtype` checados adequadamente.

Q4. Array com float e conversão para `int64`
Correto criar `arr3` e converter via `astype(np.int64)`. Observação importante: ao converter float para int, o NumPy **trunca** a parte decimal (ex.: `22.1 -> 22`). Isso precisa ser explicitado porque pode introduzir perda de informação.

Q5. “É possível criar array com floats e ints?”
Aqui está o erro conceitual:

* É possível fornecer ints e floats na mesma criação, mas o NumPy mantém **um único `dtype`** no array; por promoção de tipo, ele tende a virar `float` (ex.: `np.array([1, 2.5]).dtype` → `float`). Ou seja: você pode misturar entradas, mas o array resultante fica homogêneo em `dtype`.
* Se a intenção for misturar tipos “de verdade” (manter heterogêneo), existe `dtype=object`, mas isso perde performance e é fora do padrão para análise numérica.

Sua própria Q4 já demonstra o caso comum: ints + float → `dtype` promovido para float.

### 4) Pontos fortes

* Uso correto de `np.array` para 1D e 2D.
* Boa checagem de propriedades estruturais (`shape`, `ndim`, `dtype`).
* Reversão via slicing (boa base para pensamento vetorizado).
* Conversão de tipo com `astype` aplicada corretamente.

### 5) Pontos a melhorar (com foco em mercado)

* Precisão conceitual sobre `dtype` e promoção de tipo (isso aparece muito em pipelines reais).
* Preferir APIs específicas do NumPy quando existem (`arr.size` vs `len(arr)`), por clareza e generalização.
* Documentar efeitos colaterais de casting (perda de precisão em float → int) e, quando necessário, aplicar estratégia (round/clip/validate) antes do cast.

### 6) Reestudo recomendado (somente escopo já liberado)

* `shape` vs `ndim` vs `size`
* `dtype` e regras de promoção (type promotion)
* `astype` e efeitos de casting (principalmente float → int)
* Slicing e `np.flip`

---