# DAY 02 GPT — Mini-projeto: “Lotes de Sensores e Auditoria de Tipos (NumPy)”

Intro (escopo permitido)
Você vai montar e auditar três lotes de medições usando somente NumPy para: criar arrays 1D/2D, inspecionar `shape/ndim/size/dtype`, reverter arrays via slicing e controlar conversão de tipo com `astype(np.int64)`, incluindo o efeito de promoção de tipo (ints + floats).

Pré-requisitos (do conteudo.md)
Python puro (liberado) + NumPy do Day 02 (criação de arrays, propriedades, slicing `[::-1]`, `astype`, promoção de tipo observável via `dtype`).

Dados (reproduzível)
Use exatamente as listas abaixo no notebook:

* `batch1 = [3, 5, 8, 13, 21]`
* `batch2 = [34, 55, 89, 144, 233]`
* `batch3 = [2, 4, 6, 13.9, 18]`

Tarefas (interligadas) e entregáveis

1. Setup (5 pts)
   Importe NumPy como `np` e mostre a versão instalada (saída no notebook).

2. Construção dos lotes 1D (10 pts)
   Crie `arr1`, `arr2`, `arr3` como `ndarray` 1D a partir de `batch1`, `batch2`, `batch3`.
   Entregável: as 3 variáveis existirem e serem `ndarray`.

3. Auditoria do lote base (10 pts)
   Para `arr1`, produza um objeto Python (tuple ou dict) chamado `audit_arr1` contendo: `shape`, `size`, `ndim`, `dtype`.
   Entregável: `audit_arr1` com esses 4 campos.

4. Função de reversão (10 pts)
   Implemente `reverse_array(arr)` que retorna uma nova visão/cópia reversa usando slicing.
   Demonstre com `arr1`.
   Entregáveis: função + saída mostrando `arr1` e `reverse_array(arr1)`.

5. Matriz 2D (batch1 + batch2) (10 pts)
   Crie `mat12` (2D) combinando `arr1` e `arr2` como “duas linhas”.
   Entregável: `audit_mat12` com `shape`, `size`, `ndim`, `dtype`.

6. Matriz 2D (batch1 + batch2 + batch3) e promoção de tipo (10 pts)
   Crie `mat123` (2D) combinando `arr1`, `arr2`, `arr3` como “três linhas”.
   Entregável: `audit_mat123` com `shape`, `size`, `ndim`, `dtype`.
   Critério: você deve evidenciar (no audit) que o dtype foi promovido para float (não precisa ser exatamente `float64`, mas precisa ser “float”).

7. Conversão controlada para int64 (15 pts)
   Crie `mat123_i64 = mat123.astype(np.int64)`.
   Entregáveis:

* `audit_mat123_i64` com `shape`, `size`, `ndim`, `dtype`
* Uma checagem explícita no notebook mostrando que o valor `13.9` virou `13` após a conversão (sem “explicar demais”, só provar).

8. Função utilitária de descrição (10 pts)
   Implemente `describe_array(arr)` que retorna um `dict` com chaves: `shape`, `size`, `ndim`, `dtype` (dtype como string, ex.: `str(arr.dtype)`).
   Entregável: `report = { "arr1": ..., "arr2": ..., "arr3": ..., "mat12": ..., "mat123": ..., "mat123_i64": ... }` usando essa função.

9. Questão conceitual (10 pts)
   No notebook (Markdown ou print), responda objetivamente:
   “É possível criar um array com floats e ints?”
   Exija que sua resposta tenha:

* 1 exemplo mínimo em código (criando um array com mistura)
* a observação do `dtype` resultante (prova)
* uma frase explicando a regra: array NumPy tem `dtype` homogêneo; mistura promove o tipo.

10. Auto-validação (10 pts)
    Crie uma célula final com asserts (ou checks equivalentes) cobrindo, no mínimo:

* `arr1.shape == (5,)` e `arr1.size == 5`
* `mat12.shape == (2, 5)` e `mat12.ndim == 2`
* `mat123.shape == (3, 5)` e `mat123.dtype.kind == "f"`
* `mat123_i64.dtype == np.int64` e `mat123_i64[2, 3] == 13`

Mapa de pontos por etapa

1. 5, 2) 10, 3) 10, 4) 10, 5) 10, 6) 10, 7) 15, 8) 10, 9) 10, 10) 10. Total: 100.


In [1]:
# Preparação
batch1 = [3, 5, 8, 13, 21]
batch2 = [34, 55, 89, 144, 233]
batch3 = [2, 4, 6, 13.9, 18]

In [22]:
# funções utils

def audit_array_generator(arr):
    audit_arr = dict()
    audit_arr["shape"] = arr.shape
    audit_arr["size"] = arr.size
    audit_arr["ndim"] = arr.ndim
    audit_arr["dtype"] = arr.dtype
    return audit_arr

## Respostas DAY 02 GPT

---

1.

In [3]:
import numpy as np

print(f"NumPy versão: {np.__version__}")

NumPy versão: 2.4.1


---

2.

In [4]:
arr1 = np.array(batch1)
arr2 = np.array(batch2)
arr3 = np.array(batch3)

In [5]:
arr1

array([ 3,  5,  8, 13, 21])

In [6]:
arr2

array([ 34,  55,  89, 144, 233])

In [7]:
arr3

array([ 2. ,  4. ,  6. , 13.9, 18. ])

---

3.

In [21]:
# Usarei audit_array_generator criado por mim
audit_arr1 = audit_array_generator(arr1)
audit_arr1

{'shape': (5,), 'size': 5, 'ndim': 1, 'dtype': dtype('int64')}

---

4.

In [9]:
def reverse_array(arr):
    return arr[::-1]

In [10]:
reverse_array(arr1)

array([21, 13,  8,  5,  3])

---

5.

In [11]:
mat12 = np.array([batch1, batch2])
mat12

array([[  3,   5,   8,  13,  21],
       [ 34,  55,  89, 144, 233]])

In [12]:
audit_mat12 = audit_array_generator(mat12)
audit_mat12

{'shape': (2, 5), 'size': 2, 'ndim': 2, 'dtype': dtype('int64')}

---

6.

In [13]:
mat123 = np.array([batch1, batch2, batch3])
mat123

array([[  3. ,   5. ,   8. ,  13. ,  21. ],
       [ 34. ,  55. ,  89. , 144. , 233. ],
       [  2. ,   4. ,   6. ,  13.9,  18. ]])

In [14]:
audit_mat123 = audit_array_generator(mat123)
audit_mat123

{'shape': (3, 5), 'size': 3, 'ndim': 2, 'dtype': dtype('float64')}

---

7.

In [15]:
mat123_i64 = mat123.astype(np.int64)
mat123_i64

array([[  3,   5,   8,  13,  21],
       [ 34,  55,  89, 144, 233],
       [  2,   4,   6,  13,  18]])

In [16]:
audit_mat123_i64 = audit_array_generator(mat123_i64)
audit_mat123_i64

{'shape': (3, 5), 'size': 3, 'ndim': 2, 'dtype': dtype('int64')}

In [17]:
print(f"Valor de mat123[2,3]: {mat123[2,3]}\nValor de mat123_i64[2,3]: {mat123_i64[2,3]}")

Valor de mat123[2,3]: 13.9
Valor de mat123_i64[2,3]: 13


---

8. Não sabia que você iria pedir essa função, criei na segunda vez que você pediu por `audit`, quiz automatizar o processo. Acredito que ele está na célula acima `funções utils`;

---

9. Não, os arrays NumPy `ndarray` são homegêneos, o que significa apenas um `dtype` para todo o array, possibilitando operações vetorizadas e menos custo de memória em processos. Existe uma ordem hierarquica no modo como NumPy define o dtype do array, `int` -> `float` -> `complex` -> `object`, quanto mais a direita maior precedência;

In [18]:
exemplo = [3, 1.0, 345, -33]
exemplo_arr = np.array(exemplo)
exemplo_arr.dtype

dtype('float64')

No exemplo acima como temos um elemento do tipo `float` é ele quem decide o `dtype`.

---

10.

In [19]:
erros = []

def check(cond: bool, msg: str):
    if not cond:
        erros.append(msg)

# 1) arr1
check(arr1.shape == (5,), f"arr1.shape esperado (5,), veio {arr1.shape}")
check(arr1.size == 5,      f"arr1.size esperado 5, veio {arr1.size}")

# 2) mat12
check(mat12.ndim == 2,     f"mat12.ndim esperado 2, veio {mat12.ndim}")
check(mat12.shape == (2, 5), f"mat12.shape esperado (2, 5), veio {mat12.shape}")

# 3) mat123
check(mat123.shape == (3, 5), f"mat123.shape esperado (3, 5), veio {mat123.shape}")
check(mat123.dtype.kind == "f",
      f"mat123.dtype.kind esperado 'f' (float), veio '{mat123.dtype.kind}' (dtype={mat123.dtype})")

# 4) mat123_i64
check(mat123_i64.dtype == np.dtype(np.int64),
      f"mat123_i64.dtype esperado np.int64, veio {mat123_i64.dtype}")
check(mat123_i64[2, 3] == 13,
      f"mat123_i64[2, 3] esperado 13, veio {mat123_i64[2, 3]}")

if erros:
    raise AssertionError("Falhas nas validações:\n- " + "\n- ".join(erros))
else:
    print("OK: todas as validações passaram.")

OK: todas as validações passaram.


## Parecer DAY 02 GPT

Resultado: 82/100 → 8,2/10.

Quebra por tarefa (mapa de pontos do enunciado)

1. Setup (5) ✅ 5/5
2. Lotes 1D (10) ✅ 10/10
3. Auditoria arr1 (10) ✅ 10/10
4. Função reversão (10) ✅ 10/10
5. Matriz 2D (10) ⚠️ 7/10
6. Matriz 3 lotes + promoção (10) ⚠️ 7/10
7. astype int64 + prova (15) ⚠️ 12/15
8. describe_array + report (10) ❌ 3/10
9. Conceitual (10) ⚠️ 8/10
10. Auto-validação (10) ✅ 10/10

Principais pontos que custaram nota

1. “size” errado nas auditorias de 2D/3D. Você usou `len(arr)` dentro do `audit_array_generator`. Em arrays 2D, `len(arr)` devolve só o tamanho da primeira dimensão (ex.: 3), não o total de elementos (deveria ser 15). O correto é `arr.size`.

2. Tarefa 8 não foi entregue como solicitado. Você criou `audit_array_generator` (boa iniciativa), mas faltou implementar `describe_array(arr)` com `dtype` em string e montar o `report = {...}` com todas as chaves pedidas.

3. Conceitual (Q9): você começa com “Não”, mas o seu próprio exemplo mostra que dá para criar com mistura; o ponto correto é: “dá para misturar na entrada, mas o `ndarray` final fica homogêneo (promoção de tipo)”.

Patch mínimo para recuperar 100/100 (mantendo sua linha de solução)

```python
def audit_array_generator(arr):
    return {
        "shape": arr.shape,
        "size": arr.size,     # <- aqui
        "ndim": arr.ndim,
        "dtype": arr.dtype
    }

def describe_array(arr):
    return {
        "shape": arr.shape,
        "size": arr.size,
        "ndim": arr.ndim,
        "dtype": str(arr.dtype)  # <- string
    }

report = {
    "arr1": describe_array(arr1),
    "arr2": describe_array(arr2),
    "arr3": describe_array(arr3),
    "mat12": describe_array(mat12),
    "mat123": describe_array(mat123),
    "mat123_i64": describe_array(mat123_i64),
}
```

Sobre seus adendos do enunciado (similaridade/repetição/contexto): registrado e vou aplicar nos próximos day_XX_gpt (mais variação de estrutura, narrativa mais orgânica e tarefas menos “espelhadas”, sem prometer tudo na introdução).